### ISSUE TITLE
Supported Instructions

### ISSUE THREAD

**Issue by sinkswim** [openhwgroup/cv32e40p#15]
I am wondering if the `{FENCE, FENCE.I}` instructions will be implemented in future releases or if you plan to create new modules to handle them. I see no implementation details in this repo or the pulpino one. The only mentions are in the riscv_tracer.
Thank you.

**Comment by davideschiavone** [comment]
FENCE and FENCE.I are now both supported. Can we close the issue? @sinkswim

**Comment by Silabs-ArjanB** [comment]
We are closing this issue as it either has been fixed with the stated (merged) pull request, because it is no longer valid, or because a follow up question for further clarification or feedback remained unanswered for at least 7 days. Please do not hesitate to re-open this issue if you do not agree that the issue has been handled satisfactorily or if you have further questions.  Thank you for contributing to this core; raising issues will help to improve it.
