### ISSUE TITLE
NMI is masked by MSTATUS[MIE]

### ISSUE THREAD

**Issue by Imperas** [openhwgroup/cv32e40p#323]
@davideschiavone @MikeOpenHWGroup 
I think there is a bug with the implementation of the NMI interrupt

The interrupt is only taken if the MSTATUS[MIE] is enabled, this is not correct as NMI is by definition 'non-maskable'
From the privilege spec

> Non-maskable interrupts (NMIs) are only used for hardware error conditions, and cause an immediate jump to an implementation-defined NMI vector running in M-mode **regardless of the state of a hart’s interrupt enable bits.**

Thx
Lee

**Comment by eroom1966** [comment]
Additionally it appears that before the NMI is asserted, 
MSTATUS[MIE]=1, MSTATUS[MPIE]=0

after the NMI is taken 
MSTATUS[MIE]=0, **MSTATUS[MPIE]=0**

but I would expect MSTATUS[MPIE]=1

Thx
Lee

**Comment by Silabs-ArjanB** [comment]
Issue might relate to #336  as well.

**Comment by Silabs-ArjanB** [comment]
Hi @Imperas The NMI functionality has been removed all together. Could you please close this issue?

**Comment by Silabs-ArjanB** [comment]
We are closing this issue as it either has been fixed with the stated (merged) pull request, because it is no longer valid, or because a follow up question for further clarification or feedback remained unanswered for at least 7 days. Please do not hesitate to re-open this issue if you do not agree that the issue has been handled satisfactorily or if you have further questions.
