### ISSUE TITLE
Wrong dcsr.cause after sleep

### ISSUE THREAD

**Issue by silabs-oysteink** [openhwgroup/cv32e40p#529]
## Wrong dcsr.cause after sleep
Cause bits in dcsr seems to wrong if the first instruction decoded after WFI + debug_req_i is an EBREAK.

1. Core is sleeping
2. debug_req_i is asserted
3. Core wakes up, fetches an ebreak instruction
4. Core enters debug mode, sets cause to 0x1 (ebreak)
5. Ebreak instruction does not retire

<img width="605" alt="ebreak_2" src="https://user-images.githubusercontent.com/66771756/94662635-f7fb5f00-0308-11eb-8d10-58a897c8e485.png">

Debug spec v 0.13.2 states the following:

> If halt is requested while wfi is executing, then the hart must leave the stalled state, completing
this instruction’s execution, and then enter Debug Mode.

In this case, I would expect the core to disregard the ebreak and enter debug mode with cause=0x3 (external debugger). Instead it enters debug as if the ebreak caused it, although the ebreak does not retire.

### Component
**Component:RTL**

### Steps to Reproduce
1. Clone my fork of core-v-verif:  https://github.com/silabs-oysteink/core-v-verif.git
2. Check out branch silabs-oysteink_random-debug
3. from cv32/sim/uvmt_cv32:
4: make comp_corev-dv gen_corev-dv TEST=corev_rand_debug START_INDEX=0 NUM_TESTS=1
5: make test TEST=corev_rand_debug RUN_INDEX=0 WAVES=YES USE_ISS=NO

I've disabled the ISS as the current state of the repo requires an invalid license. Assertion will fire regardlessly.

**Comment by Silabs-ArjanB** [comment]
@silabs-PaulZ I expect that exactly the same issue will happen when we try to assert debug_req_i upon cold start while the first regular program instruction would have been an ebreak.

**Comment by silabs-PaulZ** [comment]
Thank you @silabs-oysteink for finding this. 

I submitted a fix with PR #531. This corner case occurs with WFI, reset, and also in general code execution.

Below are waveforms showing the new register ebrk_debug_entry_q that will capture if entry is due to a ebreak instruction. The top half of the waveform shows the scenario where debug_req preempts the ebreak instruction and cause is set to `haltreq`. The bottom half is where debug_req is after the taken ebreak instruction, asserting ebrk_debug_entry_q, and setting cause to `ebreak`.

![image](https://user-images.githubusercontent.com/59703134/94735827-f04fb080-0330-11eb-90e5-ffe528b34032.png)

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oysteink Thank you for finding this issue. The related PR has been merged. Can you update core-v-verif to the latest CV32E40P repos and close this issue if you agree it has been fixed?

**Comment by silabs-oysteink** [comment]
The issue is fixed, but another issue came up which seems related: If we get a debug_req_i while single stepping, we should enter debug mode with cause=3 (external request) instead of cause=4 (single step), as external debug request has higher priority than a single step.  This is captured by the same method as described above, only with updated RTL for this issue.

<img width="788" alt="debug_step_ext_1" src="https://user-images.githubusercontent.com/66771756/94789844-c00e1d80-03d5-11eb-8e44-c8c286b096ef.png">

According to debug spec 0.13.2, the priority of cause in case of multiple events is as follows (from highest to lowest):

1. Trigger match
2. Ebreak
3. resethaltreq
4. haltreq
5. step

I'm not sure if I should make a new issue or continue on this one, as they seem very related.

**Comment by silabs-PaulZ** [comment]
Hi @silabs-oysteink , I had originally made single step mask the debug_req in order to always honor the single step execution before returning back to debug mode. I see this doesn’t work well for all corner cases, such as in the case where the user keeps debug_req asserted when exiting debug mode. 

I’ve made another PR #538 which will fix this problem. 

In this wave, you can see that debug req occurs just before the instruction has an opportunity to retire and the cause = haltreq, with depc not changing.

 
![image](https://user-images.githubusercontent.com/59703134/94882103-aba93f80-042c-11eb-9248-3c1486f8f37f.png)


In this example, you can see that debug req occurs just after the instruction is retired and the cause = step, with depc incrementing to next instruction.
 
![image](https://user-images.githubusercontent.com/59703134/94882105-af3cc680-042c-11eb-9756-a5cc6e81c73d.png)

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oysteink https://github.com/openhwgroup/cv32e40p/pull/538 has been merged. If the above issue has been resolved can you please close this issue?
