### ISSUE TITLE
Extension 'zicsr' required

### ISSUE THREAD

**Issue by gullahmed1251** [openhwgroup/cv32e40p#757]
I am trying to run the core by following the [CORE-V-VERIF Verification Strategy (https://docs.openhwgroup.org/projects/core-v-verif/en/latest/quick_start.html) guide. I have followed all the mentioned steps but when i am finding an error that extension 'zicsr' not found. I am also finding few other errors too.
Kindly check the attached screenshot and help me to solve the errors.
![Error](https://user-images.githubusercontent.com/88985294/213912431-faa33cb4-316d-4abf-a04b-462ba5f6b0f3.PNG)

**Comment by abukharmeh** [comment]
It looks like the toolchain you are using wants you to explictly add ziscr to the march used to compile the BSP ! 
So maybe change rv32imc to rv32imc_zicsr in https://github.com/openhwgroup/core-v-verif/blob/0c772a395afb07bdd46aa98ed0ccb5720a99b72b/cv32e40p/bsp/Makefile#L9 ? 

IIRC, zicsr was factored out from the baseline ISA at some point https://gcc.gnu.org/pipermail/gcc-patches/2020-November/558910.html 

If the current version of corev-gcc has this behaviour, then maybe the makefile should be updated ! 

Also I feel like this issue is better suited  for core-v-verif repo ?

**Comment by gullahmed1251** [comment]
Hey, thank you so much for helping me. It worked but I found another issue, could you help me in it? This again showing that missing zicsr
![error2](https://user-images.githubusercontent.com/88985294/213914281-fed056be-2f88-40e1-b7df-a08b71083856.PNG)

**Comment by MikeOpenHWGroup** [comment]
Hi @gullahmed1251, thanks for your issue.  @abukharmeh is correct on both points:

1. You need an up to date toolchain that supports Zicsr.  Prebuilt toolchains from Embecosm.
2. This is not a CV32E40P issue, it is a CORE-V-VERIF issue.

I'll close this and if you are still having trouble after installing an up to date toolchain, please open an issue on CORE-V-VERIF.

**Comment by MikeOpenHWGroup** [comment]
Hi @aWZHY0yQH81uOYvH, this issue is closed, please do not comment further here.  The discussion has been moved to https://github.com/openhwgroup/core-v-verif/issues/1594.
