### ISSUE TITLE
Encoding of immediates for PULP SIMD instructions

### ISSUE THREAD

**Issue by jstraus59** [openhwgroup/cv32e40p#765]
The [SIMD ALU Encoding table for version 1.2.1](https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/cv32e40p_v1.2.1/instruction_set_extensions.html#simd-alu-encoding) shows the Imm6 operands are encoded in bits 25:0 as `Imm6[0|5:1]` which I would interpret to mean the 6 bit immediate value is formed with the opcode bit 20 as the MSB (imm bit 5) and opcode bits 25:21 as immediate bits 4:0, i.e.:

`imm6 = [op20|op25:21]`

This is different than the encoding described in that table in the [documentation for  version 1.1.0](https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/cv32e40p_v1.1.0/instruction_set_extensions.html#simd-alu-encoding), which shows the immediate encoded as `Imm6[5:0]` (optionaly sign extended), but with the following note at the bottom of the encoding table:

`Note: Imm6[5:0] is encoded as { Imm6[0], Imm6[5:1] }, LSB at the 25th bit of the instruction`

I would interpret `{ Imm6[0], Imm6[5:1] }` as matching the above (`imm6 = [op20|op25:21]`), but this is inconsistent with the statement `LSB at the 25th bit of the instruction` - the LSB of the immediate is bit 21 of the instruction and bit 25 of the instruction is bit 4 of the immediate in my interpretation.

Has the encoding of these immediate operands changed between version 1.1.0 and 1.2.1, or was this just a cleaner way to describe the immediate encoding in the table? 

Was the statement `LSB at the 25th bit of the instruction` simply incorrect in version 1.1.0, or am I misinterpreting something here?

Thanks

Jim Straus
Imperas

**Comment by pascalgouedo** [comment]
Hi Jim,

There is a direct position relationship between instr[25:20] and Imm6[0|5:1] which is:
Imm6[0] = instr[25] and Imm6[5:1] = instr[24:20] so

Imm6[5:0]= { instr[24:20], instr[25] }

This is reusing the same description as standard RISC-V instruction.

So both 1.1.0 and 1.2.1 are equivalent but I think it is clearer to have a full-contained encoding table rather than having notes below it that you could even not notice (was the case with first GCC toolchain).

Cheers,
Pascal.
